version: "2"
run:
  concurrency: 4
  modules-download-mode: vendor
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - ginkgolinter
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: original
          files:
            - $all
            - '!$test'
          deny:
            - pkg: k8s.io/kubernetes
              desc: Importing k8s.io/kubernetes as library is not supported
        test:
          list-mode: lax
          files:
            - $test
          deny:
            - pkg: k8s.io/kubernetes
              desc: Importing k8s.io/kubernetes as library is not supported
    errcheck:
      exclude-functions:
        - fmt.Fprintf
    ginkgolinter:
      forbid-focus-container: true
    gocritic:
      disabled-checks:
        - commentFormatting
    misspell:
      locale: US
      ignore-rules:
        - DRA
        - dra
        - NRI
        - nri
        - NUMA
        - numa
    revive:
      rules:
        - name: comment-spacings
    staticcheck:
      checks:
        - ST1008
        - ST1019
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - blank
        - default
        - prefix(k8s.io)
        - prefix(sigs.k8s.io)
        - prefix(github.com/ffromani)
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - vendor
      - pkg/version
      - third_party$
      - builtin$
      - examples$
      - cmd/*
